FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    vim \
    && rm -rf /var/lib/apt/lists/*

# current_workspace is folder in docker container
WORKDIR /current_workspace

CMD ["/bin/bash"]