version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: TaiChi
    ports:
      - "3307:3306"

  postgres:
    image: postgres:latest
    container_name: postgresql-container
    environment:
      POSTGRES_PASSWORD: TaiChi
    ports:
      - "5432:5432"
